language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - docker --version # print the version for logging
  - docker -v
  - docker-compose -v

script:
  - docker image prune --all
  - docker-compose -f docker-compose-build.yaml build --parallel
     
# Tasks to perform after the process is successful. 
# Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
# Tag images
  - docker tag udagram-frontend rasterayzer/udagram-frontend:latest
  - docker tag udagram-api-feed rasterayzer/udagram-api-feed:latest
  - docker tag udagram-api-user rasterayzer/udagram-api-user:latest
  - docker tag reverseproxy rasterayzer/udagram-reverseproxy:latest
# Push images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push rasterayzer/udagram-frontend
  - docker push rasterayzer/udagram-api-feed
  - docker push rasterayzer/udagram-api-user
  - docker push rasterayzer/udagram-reverseproxy